# Generated by Django 4.1.6 on 2023-02-04 04:01

from django.db import migrations, models
import todo.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completiondate',
            field=models.DateField(validators=[todo.models.validate_date]),
        ),
    ]
